package com.mdval.utils;

/**
 * @author federico
 *
 */
public class Constants {
	
	/**
	 * App globals
	 */
	public static final String COD_USR = "CodUsr";
	public static final String SPRING_CONTEXT = "SPRING_CONTEXT";
	
	/**
	 * Bean names
	 */
	
	
	 // CONSTANTES DE UI
	
	/**
	 * Menu de la aplicación
	 */
	public static final String MNU_DEF_GLOSARIOS = "MNU_DEF_GLOSARIOS";
	public static final String MNU_DATOS_GLOSARIO_CAMPOS = "MNU_DATOS_GLOSARIO_CAMPOS";
	public static final String MNU_DEF_NORMAS = "MNU_DEF_NORMAS";
	public static final String MNU_DEF_ELEMENTOS = "MNU_DEF_ELEMENTOS";
	public static final String MNU_DEF_ELEMENTOS_NORMA = "MNU_DEF_ELEMENTOS_NORMA";
	public static final String MNU_DEF_TIPOS_PARTICULAS = "MNU_DEF_TIPOS_PARTICULAS";
	public static final String MNU_DEF_PARTICULAS_NORMA_ELEMENTO = "MNU_DEF_PARTICULAS_NORMA_ELEMENTO";
	public static final String MNU_VALORES_PARTICULAS = "MNU_VALORES_PARTICULAS";
	public static final String MNU_COMPROBAR_NOMBRE_ELEMENTO = "MNU_COMPROBAR_NOMBRE_ELEMENTO";
	public static final String MNU_MODELOS = "MNU_MODELOS";
	
	/**
	 * Comandos que activan dialogos
	 */
	public static final String CMD_INICIAR_APP = "CMD_INICIAR_APP";
	public static final String CMD_PANEL_PRINCIPAL_TAB_EXCEPCIONES = "CMD_PANEL_PRINCIPAL_TAB_EXCEPCIONES";
	public static final String CMD_ALTA_GLOSARIOS = "CMD_ALTA_GLOSARIOS";
	public static final String CMD_MODIFICACION_GLOSARIOS = "CMD_MODIFICACION_GLOSARIOS";
	public static final String CMD_BAJA_GLOSARIO_CAMPOS = "CMD_BAJA_GLOSARIO_CAMPOS";
	public static final String CMD_ALTA_GLOSARIO_CAMPOS = "CMD_ALTA_GLOSARIO_CAMPOS";
	public static final String CMD_MODIFICACION_GLOSARIO_CAMPOS = "CMD_MODIFICACION_GLOSARIO_CAMPOS";
	public static final String CMD_ALTA_NORMAS = "CMD_ALTA_NORMAS";
	public static final String CMD_MODIFICACION_NORMAS = "CMD_MODIFICACION_NORMAS";
	public static final String CMD_ALTA_ELEMENTOS = "CMD_ALTA_ELEMENTOS";
	public static final String CMD_MODIFICACION_ELEMENTOS = "CMD_MODIFICACION_ELEMENTOS";
	public static final String CMD_ALTA_TIPOS_PARTICULA = "CMD_ALTA_TIPOS_PARTICULA";
	public static final String CMD_MODIFICACION_TIPOS_PARTICULA = "CMD_MODIFICACION_TIPOS_PARTICULA";
	public static final String CMD_ALTA_VALORES_PARTICULAS = "CMD_ALTA_VALORES_PARTICULAS";
	public static final String CMD_BAJA_VALORES_PARTICULAS = "CMD_BAJA_VALORES_PARTICULAS";
	public static final String CMD_MODIFICACION_VALORES_PARTICULAS = "CMD_MODIFICACION_VALORES_PARTICULAS";
	public static final String CMD_ALTA_MANTENIMIENTO_PARTICULAS = "CMD_ALTA_MANTENIMIENTO_PARTICULAS";
	public static final String CMD_MODIFICACION_MANTENIMIENTO_PARTICULAS = "CMD_MODIFICACION_MANTENIMIENTO_PARTICULAS";
	public static final String CMD_ALTA_MODELOS = "CMD_ALTA_MODELOS";
	public static final String CMD_MODIFICACION_MODELOS = "CMD_MODIFICACION_MODELOS";
	
	/**
	 * Panel principal
	 */
	public static final String PANEL_PRINCIPAL_BTN_SEARCH = "PANEL_PRINCIPAL_BTN_SEARCH";
	public static final String PANEL_PRINCIPAL_BTN_LOAD_SCRIPT = "PANEL_PRINCIPAL_BTN_LOAD_SCRIPT";
	public static final String PANEL_PRINCIPAL_BTN_VALIDAR = "PANEL_PRINCIPAL_BTN_VALIDAR";
	public static final String PANEL_PRINCIPAL_BTN_LIMPIAR_VALIDACION = "PANEL_PRINCIPAL_BTN_LIMPIAR_VALIDACION";
	public static final String PANEL_PRINCIPAL_BTN_LIMPIAR_TODO = "PANEL_PRINCIPAL_BTN_LIMPIAR_TODO";
	
	/**
	 * DlgIdentificador
	 */
	public static final String DLG_IDENTIFICADOR_BTN_ACEPTAR = "DLG_IDENTIFICADOR_BTN_ACEPTAR";
	
	/**
	 * DlgExcepciones
	 */
	public static final String DLG_EXCEPCIONES_BTN_ACEPTAR = "DLG_EXCEPCIONES_BTN_ACEPTAR";
	public static final String DLG_EXCEPCIONES_BTN_CANCELAR = "DLG_EXCEPCIONES_BTN_CANCELAR";
	
	/**
	 * DlgDefinicionGlosarios constantes
	 */
	public static final String DLG_DEFINICION_GLOSARIOS_SELECCIONADO = "DLG_DEFINICION_GLOSARIOS_SELECCIONADO";
	public static final String DLG_DEFINICION_GLOSARIOS_TABLA_GLOSARIOS_CABECERA = "DLG_DEFINICION_GLOSARIOS_TABLA_GLOSARIOS_CABECERA";
	public static final String DLG_DEFINICION_GLOSARIOS_BTN_BUSCAR = "DLG_DEFINICION_GLOSARIOS_BTN_BUSCAR";
	public static final String DLG_DEFINICION_GLOSARIOS_BTN_ALTA = "DLG_DEFINICION_GLOSARIOS_BTN_ALTA";
	public static final String DLG_DEFINICION_GLOSARIOS_BTN_MODIFICACION = "DLG_DEFINICION_GLOSARIOS_BTN_MODIFICACION";
	public static final String DLG_DEFINICION_GLOSARIOS_BTN_SELECCIONAR = "DLG_DEFINICION_GLOSARIOS_BTN_SELECCIONAR";
	
	/**
	 * DlgAltaModificacionGlosarios
	 */
	public static final String DLG_ALTA_MODIFICACION_GLOSARIOS_BTN_ACEPTAR = "DLG_ALTA_MODIFICACION_GLOSARIOS_BTN_ACEPTAR";
	public static final String DLG_ALTA_MODIFICACION_GLOSARIOS_BTN_CANCELAR = "DLG_ALTA_MODIFICACION_GLOSARIOS_BTN_CANCELAR";

	/**
	 * DlgGlosarioCampos
	 */
	public static final String DLG_GLOSARIO_CAMPOS_CAMPO_SELECCIONADO = "DLG_GLOSARIO_CAMPOS_CAMPO_SELECCIONADO";
	public static final String DLG_GLOSARIO_CAMPOS_TABLA_CAMPO_CABECERA = "DLG_GLOSARIO_CAMPOS_TABLA_CAMPO_CABECERA";
	public static final String DLG_GLOSARIO_CAMPOS_BTN_BUSCAR_GLOSARIO = "DLG_GLOSARIO_CAMPOS_BTN_BUSCAR_GLOSARIO";
	public static final String DLG_GLOSARIO_CAMPOS_BTN_BUSCAR = "DLG_GLOSARIO_CAMPOS_BTN_BUSCAR";
	public static final String DLG_GLOSARIO_CAMPOS_BTN_ALTA = "DLG_GLOSARIO_CAMPOS_BTN_ALTA";
	public static final String DLG_GLOSARIO_CAMPOS_BTN_BAJA = "DLG_GLOSARIO_CAMPOS_BTN_BAJA";
	public static final String DLG_GLOSARIO_CAMPOS_BTN_MODIFICACION = "DLG_GLOSARIO_CAMPOS_BTN_MODIFICACION";
	public static final String DLG_GLOSARIO_CAMPOS_BTN_IMPRIMIR = "DLG_GLOSARIO_CAMPOS_BTN_IMPRIMIR";
	
	/**
	 * DlgAltaModificacionCampos
	 */
	public static final String DLG_ALTA_MODIFICACION_CAMPOS_BTN_ACEPTAR = "DLG_ALTA_MODIFICACION_CAMPOS_BTN_ACEPTAR";
	public static final String DLG_ALTA_MODIFICACION_CAMPOS_BTN_CANCELAR = "DLG_ALTA_MODIFICACION_CAMPOS_BTN_CANCELAR";
	
	/**
	 * DlgBajaGlosario
	 */
	public static final String DLG_BAJA_GLOSARIO_BTN_ACEPTAR = "DLG_BAJA_GLOSARIO_BTN_ACEPTAR";
	public static final String DLG_BAJA_GLOSARIO_BTN_CANCELAR = "DLG_BAJA_GLOSARIO_BTN_CANCELAR";
	
	public static final String DLG_DEFINICION_NORMAS_BTN_ALTA = "DLG_DEFINICION_NORMAS_BTN_ALTA";
	public static final String DLG_DEFINICION_NORMAS_BTN_MODIFICACION = "DLG_DEFINICION_NORMAS_BTN_MODIFICACION";
	
	public static final String DLG_DEFINICION_ELEMENTOS_BTN_ALTA = "DLG_DEFINICION_ELEMENTOS_BTN_ALTA";
	public static final String DLG_DEFINICION_ELEMENTOS_BTN_MODIFICACION = "DLG_DEFINICION_ELEMENTOS_BTN_MODIFICACION";
	
	public static final String DLG_DEFINICION_TIPOS_PARTICULA_BTN_ALTA = "DLG_DEFINICION_TIPOS_PARTICULA_BTN_ALTA";
	public static final String DLG_DEFINICION_TIPOS_PARTICULA_BTN_MODIFICACION = "DLG_DEFINICION_TIPOS_PARTICULA_BTN_MODIFICACION";
	
	public static final String DLG_VALORES_PARTICULAS_BTN_ALTA = "DLG_VALORES_PARTICULAS_BTN_ALTA";
	public static final String DLG_VALORES_PARTICULAS_BTN_BAJA = "DLG_VALORES_PARTICULAS_BTN_BAJA";
	public static final String DLG_VALORES_PARTICULAS_BTN_MODIFICACION = "DLG_VALORES_PARTICULAS_BTN_MODIFICACION";
	
	public static final String DLG_MANTENIMIENTO_PARTICULAS_BTN_ALTA = "DLG_MANTENIMIENTO_PARTICULAS_BTN_ALTA";
	public static final String DLG_MANTENIMIENTO_PARTICULAS_BTN_BAJA = "DLG_MANTENIMIENTO_PARTICULAS_BTN_BAJA";
	public static final String DLG_MANTENIMIENTO_PARTICULAS_BTN_MODIFICACION = "DLG_MANTENIMIENTO_PARTICULAS_BTN_MODIFICACION";
	
	public static final String DLG_DEFINICION_MODELOS_BTN_ALTA = "DLG_DEFINICION_MODELOS_BTN_ALTA";
	public static final String DLG_DEFINICION_MODELOS_BTN_MODIFICACION = "DLG_DEFINICION_MODELOS_BTN_MODIFICACION";
}
