/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sapiens.app.ui.normasnomenclatura;

import java.awt.Dimension;
import java.awt.Font;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import com.sapiens.app.ui.utils.FrameSupport;

/**
 *
 * @author federico
 */
public class FrmModificacionNormas extends FrameSupport {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7468072915163364659L;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton btnAceptar;
	private JButton btnAltaElemento;
	private JButton btnBajaElemento;
	private JButton btnCancelar;
	private JButton btnModificacionElemento;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JLabel jLabel4;
	private JLabel jLabel5;
	private JLabel jLabel6;
	private JLabel jLabel7;
	private JScrollPane jScrollPane1;
	private JScrollPane jScrollPane2;
	private JTable tblElementos;
	private JTable tblParticulas;
	private JTextField txtCodigo;
	private JTextField txtDescripcion;
	private JTextField txtFecha;
	private JTextField txtUsuario;
	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new form DlgModificacionNormas
	 */
	public FrmModificacionNormas() {
		super();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	protected void initComponents() {

		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		txtCodigo = new JTextField();
		txtDescripcion = new JTextField();
		jLabel4 = new JLabel();
		btnAltaElemento = new JButton();
		btnBajaElemento = new JButton();
		btnModificacionElemento = new JButton();
		jScrollPane1 = new JScrollPane();
		tblElementos = new JTable();
		jLabel5 = new JLabel();
		jScrollPane2 = new JScrollPane();
		tblParticulas = new JTable();
		jLabel6 = new JLabel();
		txtUsuario = new JTextField();
		jLabel7 = new JLabel();
		txtFecha = new JTextField();
		btnAceptar = new JButton();
		btnCancelar = new JButton();

		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

		panelLogo.setPreferredSize(new Dimension(286, 63));

		GroupLayout panelLogoLayout = new GroupLayout(panelLogo);
		panelLogo.setLayout(panelLogoLayout);
		panelLogoLayout.setHorizontalGroup(
				panelLogoLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 286, Short.MAX_VALUE));
		panelLogoLayout.setVerticalGroup(
				panelLogoLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 67, Short.MAX_VALUE));

		jLabel1.setFont(new Font("Dialog", 1, 18)); // NOI18N
		jLabel1.setText("Alta/Modificación de Norma Completa");

		jLabel2.setText("Código");

		jLabel3.setText("Descripción");

		txtCodigo.setEditable(false);
		txtCodigo.setEnabled(false);
		txtCodigo.setPreferredSize(new Dimension(4, 27));

		txtDescripcion.setMinimumSize(new Dimension(4, 27));
		txtDescripcion.setPreferredSize(new Dimension(64, 27));

		jLabel4.setText("Elementos:");

		btnAltaElemento.setText("ALTA");
		btnAltaElemento.setPreferredSize(new Dimension(130, 27));

		btnBajaElemento.setText("BAJA");
		btnBajaElemento.setPreferredSize(new Dimension(130, 27));

		btnModificacionElemento.setText("MODIFICACION");

		tblElementos.setModel(new DefaultTableModel(
				new Object[][] { { null, null, null, null, null }, { null, null, null, null, null },
						{ null, null, null, null, null }, { null, null, null, null, null } },
				new String[] { "CE", "DES_ELEMENTO", "MAX", "EXPRESION_REGULAR_ASOCIADA", "TXT_FORMATO" }) {
			Class[] types = new Class[] { java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class,
					java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tblElementos);

		jLabel5.setText("Partículas:");

		tblParticulas
				.setModel(new DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane2.setViewportView(tblParticulas);

		jLabel6.setText("Usuario:");

		txtUsuario.setPreferredSize(new Dimension(64, 27));

		jLabel7.setText("Fecha:");

		txtFecha.setPreferredSize(new Dimension(64, 27));

		btnAceptar.setText("ACEPTAR");
		btnAceptar.setPreferredSize(new Dimension(98, 27));

		btnCancelar.setText("CANCELAR");

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(panelLogo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel1)
						.addGap(573, 679, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
						.addGroup(layout.createSequentialGroup().addGap(139, 139, 139).addComponent(jLabel6)
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(txtUsuario, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jLabel7).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(txtFecha, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
								.createParallelGroup(GroupLayout.Alignment.TRAILING)
								.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 610, GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel3).addComponent(jLabel2))
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
												.addComponent(txtDescripcion, GroupLayout.PREFERRED_SIZE, 485,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(txtCodigo, GroupLayout.PREFERRED_SIZE, 97,
														GroupLayout.PREFERRED_SIZE)))))
						.addGroup(layout.createSequentialGroup().addGap(34, 34, 34).addComponent(jLabel4)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(btnAltaElemento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnBajaElemento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnModificacionElemento)))
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(26, 26, 26).addComponent(jLabel5)
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jScrollPane2)
										.addContainerGap())))
				.addGroup(GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnAceptar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(btnCancelar)
								.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(panelLogo, GroupLayout.PREFERRED_SIZE, 67,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1))
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2).addComponent(txtCodigo, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(txtDescripcion, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
												.addComponent(btnAltaElemento, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(btnBajaElemento, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(btnModificacionElemento).addComponent(jLabel5))
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
										.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel6)
										.addComponent(txtUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel7).addComponent(txtFecha, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(btnCancelar).addComponent(btnAceptar, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	@Override
	protected void initEvents() {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void initialState() {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void setupLiterals() {
		// TODO Auto-generated method stub
		
	}
}
