/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sapiens.app.ui.normasnomenclatura;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import com.sapiens.app.ui.utils.FrameSupport;

/**
 *
 * @author federico
 */
public class FrmMantenimientoParticulas extends FrameSupport {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3576255765784636736L;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton btnAceptar;
	private JButton btnAltaElemento;
	private JButton btnBajaElemento;
	private JButton btnCancelar;
	private JButton btnModificacionElemento;
	private JComboBox<String> cmbProyecto;
	private JComboBox<String> cmbSubproyecto;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JLabel jLabel5;
	private JLabel jLabel6;
	private JLabel jLabel7;
	private JScrollPane jScrollPane1;
	private JPanel panelBotones;
	private JPanel panelTabla;
	private JTable tblValoresPosibles;
	private JTextField txtCodigo;
	private JTextField txtDescripcion;
	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new form DlgModificacionNormas
	 */
	public FrmMantenimientoParticulas() {
		super();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	protected void initComponents() {

		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		txtCodigo = new JTextField();
		txtDescripcion = new JTextField();
		jLabel5 = new JLabel();
		jLabel6 = new JLabel();
		cmbProyecto = new JComboBox<>();
		jLabel7 = new JLabel();
		cmbSubproyecto = new JComboBox<>();
		panelTabla = new JPanel();
		jScrollPane1 = new JScrollPane();
		tblValoresPosibles = new JTable();
		panelBotones = new JPanel();
		btnAltaElemento = new JButton();
		btnBajaElemento = new JButton();
		btnModificacionElemento = new JButton();
		btnAceptar = new JButton();
		btnCancelar = new JButton();

		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

		panelLogo.setPreferredSize(new Dimension(286, 63));

		GroupLayout panelLogoLayout = new GroupLayout(panelLogo);
		panelLogo.setLayout(panelLogoLayout);
		panelLogoLayout.setHorizontalGroup(
				panelLogoLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 286, Short.MAX_VALUE));
		panelLogoLayout.setVerticalGroup(
				panelLogoLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 67, Short.MAX_VALUE));

		jLabel1.setFont(new Font("Dialog", 1, 18)); // NOI18N
		jLabel1.setText("Asignación de Valores a los Tipos de Partícula");

		jLabel2.setText("Código");

		jLabel3.setText("Descripción");

		txtCodigo.setPreferredSize(new Dimension(4, 27));

		txtDescripcion.setMinimumSize(new Dimension(4, 27));
		txtDescripcion.setPreferredSize(new Dimension(64, 27));

		jLabel5.setText("Valores posibles de las partículas");

		jLabel6.setText("Proyecto");

		cmbProyecto.setModel(new DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
		cmbProyecto.setSelectedIndex(1);

		jLabel7.setText("Subproyecto");

		cmbSubproyecto.setModel(new DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
		cmbSubproyecto.setSelectedIndex(1);

		panelTabla.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));

		tblValoresPosibles.setModel(new DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null }, { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null } },
				new String[] { "COD_PARTICULA", "VAL_PARTICULA", "DES_VAL_PART", "Proyecto", "Subproyecto", "COD_USR",
						"FEC_ACTU" }));
		jScrollPane1.setViewportView(tblValoresPosibles);

		btnAltaElemento.setText("ALTA");
		btnAltaElemento.setPreferredSize(new Dimension(130, 27));
		panelBotones.add(btnAltaElemento);

		btnBajaElemento.setText("BAJA");
		btnBajaElemento.setPreferredSize(new Dimension(130, 27));
		panelBotones.add(btnBajaElemento);

		btnModificacionElemento.setText("MODIFICACION");
		panelBotones.add(btnModificacionElemento);

		GroupLayout panelTablaLayout = new GroupLayout(panelTabla);
		panelTabla.setLayout(panelTablaLayout);
		panelTablaLayout.setHorizontalGroup(panelTablaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(panelTablaLayout.createSequentialGroup().addContainerGap()
						.addGroup(panelTablaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1).addComponent(panelBotones, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		panelTablaLayout.setVerticalGroup(panelTablaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(panelBotones,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		btnAceptar.setText("ACEPTAR");
		btnAceptar.setPreferredSize(new Dimension(130, 27));

		btnCancelar.setText("CANCELAR");
		btnCancelar.setPreferredSize(new Dimension(130, 27));

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(panelTabla, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap())
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(panelLogo, GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jLabel1))
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
																.addGap(22, 22, 22).addComponent(
																		txtCodigo, GroupLayout.PREFERRED_SIZE, 212,
																		GroupLayout.PREFERRED_SIZE))
														.addGroup(layout
																.createSequentialGroup().addComponent(jLabel6)
																.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		cmbProyecto, GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE)))
														.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(layout
																.createParallelGroup(GroupLayout.Alignment.LEADING)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(jLabel7)
																		.addPreferredGap(
																				LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				cmbSubproyecto,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				LayoutStyle.ComponentPlacement.RELATED,
																				GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(jLabel3)
																		.addPreferredGap(
																				LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(txtDescripcion,
																				GroupLayout.PREFERRED_SIZE, 304,
																				GroupLayout.PREFERRED_SIZE)
																		.addGap(0, 0, Short.MAX_VALUE)))))
										.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel5).addContainerGap(1128,
										Short.MAX_VALUE))))
				.addGroup(GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnAceptar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnCancelar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(panelLogo, GroupLayout.PREFERRED_SIZE, 67,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1))
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
												.addComponent(txtCodigo, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(txtDescripcion, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 27,
														GroupLayout.PREFERRED_SIZE))
								.addGap(10, 10, 10)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel6)
										.addComponent(cmbProyecto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel7).addComponent(cmbSubproyecto, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18).addComponent(jLabel5)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(
										panelTabla, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(btnAceptar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(btnCancelar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	@Override
	protected void initEvents() {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void initialState() {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void setupLiterals() {
		// TODO Auto-generated method stub
		
	}
}
