/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sapiens.app.ui.validacionscripts;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.WindowConstants;

import com.sapiens.app.ui.listener.DlgExcepcionesListener;
import com.sapiens.app.utils.Constants;

/**
 *
 * @author federico
 */
public class DlgExcepciones extends JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6665571236064538468L;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton btnAceptar;
	private JButton btnCancelar;
	private JLabel jLabel1;
	private JScrollPane jScrollPane1;
	private JPanel panelBotones;
	private JTextArea txtComentario;
	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new form DlgExcepciones
	 */
	public DlgExcepciones(Frame frame, boolean modal) {
		super(frame, modal);
		initComponents();
		initEvents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new JLabel();
		jScrollPane1 = new JScrollPane();
		txtComentario = new JTextArea();
		panelBotones = new JPanel();
		btnAceptar = new JButton();
		btnCancelar = new JButton();

		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("Comentario:");
		getContentPane().add(jLabel1, BorderLayout.PAGE_START);

		txtComentario.setColumns(20);
		txtComentario.setRows(5);
		jScrollPane1.setViewportView(txtComentario);

		getContentPane().add(jScrollPane1, BorderLayout.CENTER);

		panelBotones.setLayout(new FlowLayout(FlowLayout.RIGHT));

		btnAceptar.setIcon(new ImageIcon(getClass().getResource("/checked.png"))); // NOI18N
		btnAceptar.setText("Aceptar");
		btnAceptar.setName(Constants.DLG_EXCEPCIONES_BTN_ACEPTAR);
		panelBotones.add(btnAceptar);

		btnCancelar.setIcon(new ImageIcon(getClass().getResource("/close.png"))); // NOI18N
		btnCancelar.setText("Cancelar");
		btnCancelar.setName(Constants.DLG_EXCEPCIONES_BTN_CANCELAR);
		panelBotones.add(btnCancelar);

		getContentPane().add(panelBotones, BorderLayout.PAGE_END);

		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void initEvents() {
		ActionListener actionListener = new DlgExcepcionesListener(this);
		
		btnAceptar.addActionListener(actionListener);
		btnCancelar.addActionListener(actionListener);
	}
}
